# Gradle Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod Properties
mod_version=1.0.0
maven_group=com.lightweightclient
archives_base_name=lightweight-client-mod
mod_id=lightweightclient

# Fabric Properties
minecraft_version=1.21.11
loader_version=0.18.1
fabric_version=0.140.0+1.21.11
